import Layout from '@/components/layouts/Layout'
// import 'bootstrap/dist/css/bootstrap.css'
import type { Metadata } from 'next'
import './globalStyles/normalize.css'

import './globalStyles/auth-popup.css'
import './globalStyles/breadcrumbs.css'
import './globalStyles/cart-popup.css'
import './globalStyles/catalog-menu.css'
import './globalStyles/cookie-popup.css'
import './globalStyles/footer.css'
import './globalStyles/globals.css'
import './globalStyles/header-profile.css'
import './globalStyles/header.css'
import './globalStyles/map.css'
import './globalStyles/menu.css'
import './globalStyles/mobile-navbar.css'
import './globalStyles/search-modal.css'
import './globalStyles/slick-theme.css'
import './globalStyles/slick.css'

export const metadata: Metadata = {
  title: 'Ростелеком',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  )
}
