import Layout from '@/components/layouts/Layout'
// import 'bootstrap/dist/css/bootstrap.css'
import type { Metadata } from 'next'
import './globalStyles/normalize.css'

import './globalStyles/globals.css'

export const metadata: Metadata = {
  title: 'Ростелеком',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  )
}
